[tool.poetry]
name = "pjecz-pagos-cliente-flask"
version = "1.0.0"
description = "Front-End del Portal de Pagos hecho con Flask."
authors = ["Guillermo Valdes <guillermo.valdes@pjecz.gob.mx>"]
license = "AGPL3"

[tool.poetry.dependencies]
python = "^3.10"
Flask = "^2.2.2"
Flask-WTF = "^1.1.1"
hashids = "^1.3.1"
Jinja2 = "^3.1.2"
python-dotenv = "^0.21.1"
requests = "^2.28.2"
Unidecode = "^1.3.6"

[tool.poetry.dev-dependencies]
pylint = "^2.15.10"
black = "^22.12.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.black]
line-length = 256
